bitbucket:
  image: frootdock/atlassian-bitbucket
  restart: always
  links:
    - database
  volumes:
    - home:/opt/bitbucket-home

database:
  image: postgres:9.4
  restart: always
  volumes:
    - data:/var/lib/postgresql/data
    - setup-bitbucket-db.sh:/docker-entrypoint-initdb.d/setup-bitbucket-db.sh
