bitbucket:
  extends:
    file: bitbucket.yml
    service: bitbucket
  ports:
    - "80:7990"
    - "8022:7999" # ssh port
  links:
    - database
  volumes:
    - home:/opt/bitbucket-home

database:
  image: postgres:9.4
  volumes:
    - setup-bitbucket-db.sh:/docker-entrypoint-initdb.d/setup-bitbucket-db.sh
